### ISSUE TITLE
Multiple searchbox with same model in same page

### ISSUE THREAD

**Issue by theazharul** [russelldavies/elm-ui-searchbox#2]
How to set unique identifier for multiple searchbox with same model in same page?

**Comment by russelldavies** [comment]
Either you can use two different `Msg` variants. For example:
```
type Msg
    = ChangedFooSearchBox (SearchBox.ChangeEvent Foo)
    | ChangedBarSearchBox (SearchBox.ChangeEvent Bar)
```

Or a single one with a tag preceding the `SearchBox.ChangeEvent a` type.
